# ------------------------ #
#    Nicknames Ultimate    #
#       by kruthers        #
# ------------------------ #
# for help and details on the different sections view: https://github.com/kruthers/Nicknames-Ultimate/wiki/Config
# DO NOT update config-version, doing this can cause permanent damage to any storage and damage the config file its self
config-version: 0.0
storage:
  type: file
  autosave_data: true
  database:
    host: 0.0.0.0
    port: 3306
    database: ''
    username: ''
    password: ''
nickname_settings:
  prefix: '~'
  max_length: 16
  min_length: 3
  fuzzy_checks: 100
  check_duplicate: true
  check_if_user: true
  block_formatting: false
  blocked_words:
    - fuck
    - shit
  check_on_join: true
display_name:
  set_player_list: true
  player_list_format: '{display_name}'
  set_nametag: true
  nametag_format: '{display_name}'
messages:
  unknown_error: '&4An Unknown error occurred when executing that command, please try again later'
  no_permission: '&4You dont have permission to run that command'
  nickname:
    too_short: '&4Sorry, that nickname is too short'
    too_long: '&4Sorry, that nickname is too long'
    taken: '&4Sorry, that name is already in use'
    illegal_formatting: '&4Sorry, that nickname contains blocked/ invalid formatting, please try again'
    banned_word: '&4Sorry, that nickname contains a blocked word'
    username: '&4Sorry, nicknames cant be other players names'
